name: "My Composite Action"
description: "Runs Harden Runner conditionally"
inputs:
  github-token:
    description: 'Github token to use to authenticate downloads'
    required: false
    default: ${{ github.token }}
    
runs:
  using: "composite"
  steps:
    - name: Harden Runner
      if: ${{ github.ref == 'refs/heads/xxxx' }}
      uses: step-security/harden-runner@9af89fc71515a100421586dfdb3dc9c984fbf411 # v2.19.4
      with:
        egress-policy: audit

    - name: Another Action
      uses: actions/checkout@v4
