name: Reusable workflow example

on:
  workflow_call:
    
permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Harden Runner
      uses: step-security/harden-runner@eb238b55efaa70779f274895e782ed17c84f2895 # v2.6.1
      with:
        egress-policy: block
        allowed-endpoints: >
          acghubeus0.actions.githubusercontent.com:443
          api.github.com:443
          github.com:443
          objects.githubusercontent.com:443
          *.golang.org:443
    - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0
    - uses: actions/setup-go@93397bea11091df50f3d7e59dc26a7711a8bcfbe # v4.1.0
      with:
        go-version: '1.17'
    - run: go build
