name: Deploy to AWS
on: 
  workflow_dispatch:
  
jobs:
  publish:
    name: Deploy to AWS
    runs-on: ubuntu-24.04
    permissions:
      contents: read      
    steps:  
        - name: Harden the runner (Audit all outbound calls)
          uses: step-security/harden-runner@5ef0c079ce82195b2a36a210272d6b661572d83e # v2.14.2
          with:
            egress-policy: audit

        - name: Checkout
          uses: actions/checkout@v2    
        - name: Retry Logic
          uses: nick-fields/retry@ce71cc2ab81d554ebbe88c79ab5975992d79ba08 # v3.0.2
          with:
            timeout_minutes: 10
            max_attempts: 3
            shell: pwsh
            command: dir
