name: Issue assignment

on:
    issues:
        types: [opened]

jobs:
    auto-assign:
        runs-on: ubuntu-24.04
        permissions:
            issues: write
        steps:
            - name: Harden the runner (Audit all outbound calls)
              uses: step-security/harden-runner@5ef0c079ce82195b2a36a210272d6b661572d83e # v2.14.2
              with:
                egress-policy: audit

            - name: 'Auto-assign issue'
              uses: pozil/auto-assign-issue@e0a56afd8846954587b00fff254caf1ec918554e # v1
              with:
                  assignees: ashishkurmi
                  numOfAssignee: 1
                  allowSelfAssign: true
