name: Pwn Request
on:
  pull_request_target:

jobs:
  build:
    name: Build and test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@ee0669bd1cc54295c223e0bb666b733df41de1c5 # v2.7.0
      with:
        ref: ${{ github.event.pull_request.head.sha }}

    - uses: actions/setup-node@f1f314fca9dfce2769ece7d933488f076716723e # v1.4.6
    - run: |
        npm install
        npm build

    
